# Pipeline
name: First Workflow

# Set trigger events
on:
  push:
  branches:
  workflow_dispatch:

# Jobs
jobs:
  print_message:
    runs-on: ubuntu-latest

    steps:
      - name: Print welcome message
        run: echo "Welcome to GitHub"