
# pipeline 
name: first workflow

#set triggers 
on:
  push:
    branches:
      -main
#jobs
jobs:
  print_message:
    runs-on: ubuntu-latest

    steps:
      - name: Print welcome message
        run: echo "Welcome to GitHub"
    steps:
      - name: Print hello message
        run: echo "hello friends"

